name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform-check:
    name: Check Terraform Security Policies with OPA
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install OPA
      run: |
        wget https://github.com/open-policy-agent/opa/releases/download/v0.55.0/opa_linux_amd64
        chmod +x opa_linux_amd64
        sudo mv opa_linux_amd64 /usr/local/bin/opa

    - name: Run OPA Policy Check
      run: opa eval --data policy/ --input terraform/modules/deployments --format=json 'data.kubernetes.security.deny'

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: terraform-check

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-python-api:${{ github.run_number }} .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-python-api:${{ github.run_number }}

  deploy:
    name: Deploy to Azure Kubernetes Service (AKS)
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      run: terraform init -input=false

    - name: Terraform Plan
      run: terraform plan -input=false -out=tfplan

    - name: Terraform Apply
      run: terraform apply -input=false tfplan
